In [39]:
import numpy as np
import pandas as pd

In [40]:
def distance(B):
        dist_matrix=np.zeros((len(B),len(B)))
        for i in range(len(B)):
                for j in range(len(B)):
                        dist_matrix[i,j]=np.sum(np.abs(B[i]-B[j]))
        return dist_matrix


In [42]:
df1=pd.read_csv("0201새벽.csv")

FileNotFoundError: [Errno 2] No such file or directory: '0201새벽.csv'

In [31]:
df1=pd.read_csv("C:/Users/vjame/git/design/0201새벽.csv").dropna()
df2=pd.read_csv("C:/Users/vjame/git/design/0202새벽.csv").dropna()
df=pd.concat([df1,df2])

In [10]:
xy=np.vstack([df1[["x좌표","y좌표"]].to_numpy(),df2[["x좌표","y좌표"]].to_numpy()])

In [11]:
xy

array([[127.01372482,  37.55578326],
       [127.01256006,  37.5565914 ],
       [127.01244746,  37.55597667],
       [127.01159494,  37.55614281],
       [127.01317892,  37.55864876],
       [127.01514913,  37.56032618],
       [127.01266486,  37.55994184],
       [127.01035985,  37.56412539],
       [127.00292074,  37.56323662],
       [126.99375528,  37.56130484],
       [126.98141426,  37.5616652 ],
       [126.9685024 ,  37.56159516],
       [126.97358438,  37.56263706],
       [126.98368685,  37.56063795],
       [126.99833066,  37.56219383],
       [127.01625413,  37.55937801],
       [127.01171345,  37.55619352],
       [127.01283649,  37.55890081],
       [127.0181571 ,  37.56110674],
       [127.01539333,  37.56395095],
       [127.01536497,  37.56476095],
       [127.01254998,  37.56333302],
       [127.01185363,  37.56311605],
       [127.01270995,  37.56353294],
       [127.0117471 ,  37.56367251],
       [127.01083625,  37.56411607],
       [126.9762387 ,  37.56041189],
 

In [14]:
dist_matrix=np.triu(distance(xy))
display(pd.DataFrame(dist_matrix))

0         1         2         3         4         5         6         7   \
0   0.0  0.001973  0.001471  0.002489  0.003411  0.005967  0.005219  0.011707   
1   0.0  0.000000  0.000727  0.001414  0.002676  0.006324  0.003455  0.009734   
2   0.0  0.000000  0.000000  0.001019  0.003404  0.007051  0.004183  0.010236   
3   0.0  0.000000  0.000000  0.000000  0.004090  0.007738  0.004869  0.009218   
4   0.0  0.000000  0.000000  0.000000  0.000000  0.003648  0.001807  0.008296   
5   0.0  0.000000  0.000000  0.000000  0.000000  0.000000  0.002869  0.008588   
6   0.0  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.006489   
7   0.0  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
8   0.0  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
9   0.0  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
10  0.0  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
11  0.0  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
12  0.0  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
13  0.0  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
14  0.0  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
15  0.0  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
16  0.0  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
17  0.0  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
18  0.0  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
19  0.0  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
20  0.0  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
21  0.0  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
22  0.0  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
23  0.0  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
24  0.0  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
25  0.0  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
26  0.0  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
27  0.0  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
28  0.0  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
29  0.0  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
30  0.0  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
31  0.0  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
32  0.0  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
33  0.0  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
34  0.0  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
35  0.0  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
36  0.0  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
37  0.0  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
38  0.0  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
39  0.0  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
40  0.0  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
41  0.0  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
42  0.0  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
43  0.0  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
44  0.0  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
45  0.0  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
46  0.0  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
47  0.0  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
48  0.0  0.000000  0.000000  0.00000

In [18]:
# 특정 임계값 설정
threshold = 0.0003

# 두 조건을 모두 만족하는 마스크 생성
mask = np.logical_and(dist_matrix < threshold, dist_matrix != 0)

# 조건을 만족하는 값들의 인덱스 찾기
indices = np.where(mask)

# 결과 출력
print("원본 행렬:")
print(dist_matrix)
print("임계값보다 작고 0이 아닌 요소들의 위치와 값:")
edges=[]
# 인덱스와 값을 함께 출력
for i, j in zip(indices[0], indices[1]):
    print(f"위치: ({i}, {j}), 값: {dist_matrix[i, j]}")
    edges.append((i,j))


원본 행렬:
[[0.         0.00197291 0.00147077 ... 0.01073783 0.01028799 0.01113044]
 [0.         0.         0.00072734 ... 0.00876492 0.00831508 0.00915753]
 [0.         0.         0.         ... 0.00926706 0.00881722 0.00965967]
 ...
 [0.         0.         0.         ... 0.         0.00044984 0.00045883]
 [0.         0.         0.         ... 0.         0.         0.00084245]
 [0.         0.         0.         ... 0.         0.         0.        ]]
임계값보다 작고 0이 아닌 요소들의 위치와 값:
위치: (0, 35), 값: 0.0002776960585109123
위치: (1, 34), 값: 0.0002772525324061803
위치: (3, 16), 값: 0.00016921601029906697
위치: (6, 45), 값: 0.00020781786849255468
위치: (18, 44), 값: 6.87080614980573e-05
위치: (29, 42), 값: 0.00017576188439250018
위치: (29, 43), 값: 0.00024248046339181428
위치: (42, 43), 값: 0.0001238657469926352


In [19]:
edges

[(0, 35), (1, 34), (3, 16), (6, 45), (18, 44), (29, 42), (29, 43), (42, 43)]

In [20]:
import networkx as nx

# 네트워크 생성
G = nx.Graph()

# 모든 지역 0~49를 노드로 추가 (50은 포함되지 않았다고 가정)
for i in range(50):
    G.add_node(i)

# 엣지를 그래프에 추가
for row, col in edges:
    G.add_edge(row, col)

# 연결된 컴포넌트 찾기
connected_components = list(nx.connected_components(G))

# 각 연결된 컴포넌트의 노드 출력
print("각 연결된 컴포넌트의 노드:")
for i, component in enumerate(connected_components, start=1):
    print(f"컴포넌트 {i}: {sorted(component)}")


각 연결된 컴포넌트의 노드:
컴포넌트 1: [0, 35]
컴포넌트 2: [1, 34]
컴포넌트 3: [2]
컴포넌트 4: [3, 16]
컴포넌트 5: [4]
컴포넌트 6: [5]
컴포넌트 7: [6, 45]
컴포넌트 8: [7]
컴포넌트 9: [8]
컴포넌트 10: [9]
컴포넌트 11: [10]
컴포넌트 12: [11]
컴포넌트 13: [12]
컴포넌트 14: [13]
컴포넌트 15: [14]
컴포넌트 16: [15]
컴포넌트 17: [17]
컴포넌트 18: [18, 44]
컴포넌트 19: [19]
컴포넌트 20: [20]
컴포넌트 21: [21]
컴포넌트 22: [22]
컴포넌트 23: [23]
컴포넌트 24: [24]
컴포넌트 25: [25]
컴포넌트 26: [26]
컴포넌트 27: [27]
컴포넌트 28: [28]
컴포넌트 29: [29, 42, 43]
컴포넌트 30: [30]
컴포넌트 31: [31]
컴포넌트 32: [32]
컴포넌트 33: [33]
컴포넌트 34: [36]
컴포넌트 35: [37]
컴포넌트 36: [38]
컴포넌트 37: [39]
컴포넌트 38: [40]
컴포넌트 39: [41]
컴포넌트 40: [46]
컴포넌트 41: [47]
컴포넌트 42: [48]
컴포넌트 43: [49]


In [24]:
lst=[]
for i in connected_components:
          lst.append(min(i))

In [35]:
lst

[0,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 36,
 37,
 38,
 39,
 40,
 41,
 46,
 47,
 48,
 49]

In [37]:
df.iloc[lst].to_csv("result3.csv")

In [29]:
pd.DataFrame(xy[lst])#.to_csv("result2.csv")

0          1
0   127.013725  37.555783
1   127.012560  37.556591
2   127.012447  37.555977
3   127.011595  37.556143
4   127.013179  37.558649
5   127.015149  37.560326
6   127.012665  37.559942
7   127.010360  37.564125
8   127.002921  37.563237
9   126.993755  37.561305
10  126.981414  37.561665
11  126.968502  37.561595
12  126.973584  37.562637
13  126.983687  37.560638
14  126.998331  37.562194
15  127.016254  37.559378
16  127.012836  37.558901
17  127.018157  37.561107
18  127.015393  37.563951
19  127.015365  37.564761
20  127.012550  37.563333
21  127.011854  37.563116
22  127.012710  37.563533
23  127.011747  37.563673
24  127.010836  37.564116
25  126.976239  37.560412
26  126.976201  37.564027
27  127.010443  37.563293
28  127.014677  37.560011
29  127.014463  37.559799
30  127.014525  37.557080
31  127.013524  37.557268
32  127.014143  37.556427
33  127.011796  37.556485
34  127.012417  37.555580
35  127.013162  37.555302
36  127.011657  37.555860
37  127.012099  37.556944
38  127.014158  37.559845
39  127.010410  37.564379
40  126.971727  37.559703
41  127.010300  37.563097
42  127.010407  37.562754